tools/timeliner/default.nix

Here is an example of generating PNG visualizations for ~/shm.tar.xz:
studio$ nix-build - <<EOF
let timeliner = (import tools/timeliner {}); in
timeliner.visualize (timeliner.summary ~/shm.tar.xz)
EOF
studio$ ls -1 result
breath_duration.png
breath_efficiency.png
breath_outliers.png
callback_efficiency.png
... where ~/shm.tar.xz is a file containing the contents of a Snabb shm directory.
The nice thing is that nix will take care of installing the right versions of all the relevant R libraries, which would be a major pain in the patootie to do by hand.

timeliner/default.nix: Add nix API to timeliner

---

tools/vmprofiler/default.nix
tools/vmprofiler/vmprofiler.R

Added a simple nix API to vmprofiler. You can run it like this:
$ git clone https://github.com/studio/studio
$ nix-build -E '(import studio/tools/vmprofiler {}).analyze_dir(/var/run/snabb/12345/engine/vmprofile)'
which will create output like this:
```
$ ls -1 result/
gc.csv
gc.txt
overview.csv
overview.txt
what.csv
what.txt
where.csv
where.txt
```
This is not the most convenient interface in the world, but it's a start!

vmprofiler nix API

---

bin/studio
nix/import.nix
nix/pkgs.nix
tools/snabbr/default.nix
tools/snabbr/latencyr.R
tools/snabbr/processes.Rmd
tools/snabbr/snabbr.R
tools/snabbr/timeliner.R
tools/snabbr/vmprofiler.R
tools/vmprofiler/vmprofiler.R

This branch introduces the shell command `studio` that serves as a multi-purpose front-end to the project. Currently there is one command supported:
```
studio process [-g groupname] <shmfolder> ...
```
This command creates a report on a set of Snabb processes that can optionally be categorized into named groups (for group-wise comparison.) Essentially it looks into the "shm" (shared memory objects) folders of the processes and analyzes the relevant data: latency histogram, timelines, vmprofiles. So it can report a lot of details about performance and make comparisons between processes and groups.
Just now this is rough and only the latency data is shown. However, it's a big milestone for me because it is the first time that I have been able to run a shell one-liner that does a whole …

Create 'studio' front-end with snabb process report

---

bin/studio
nix/pkgs.nix
tools/snabbr/default.nix

New command:
studio snabb rstudio
Runs the RStudio IDE (https://www.rstudio.com) with the snabbr libraries loaded and the same versions of all R packages that the rest of Studio uses.
This is to make it easy to hack R code and know that it will run the same under nix. R has a big ecosystem with lots of libraries being updated etc so compatibility problems are common if you use different versions for development and deployment.
also updated Studio to use the latest version of nixpkgs.

Add command: studio snabb rstudio

---

bin/studio
nix/import.nix
tools/snabbr/default.nix
tools/snabbr/snabbr.R
tools/snabbr/vmprofiler.R

Add the command `studio snabb vmprofile <dir>` to analyze VMProfile data for one Snabb process. Creates `./result` directory containing a small set of numeric reports in both .txt and .csv formats.
Example output:
```
[luke@interlaken:~/git/studio]$ bin/studio snabb vmprofile ~/git/snabb/src/shm/6841                                                                                                                                 
created ./result -> /nix/store/vx5yb53d6vf1jscl6ih0qd0bw28zxbaf-snabb-process-vmprofile
[luke@interlaken:~/git/studio]$ ls result
gc.csv  gc.txt  overview.csv  overview.txt  what.csv  what.txt  where.csv  where.txt
[luke@interlaken:~/git/studio]$ cat result/overview.txt 
profile percent
apps.socket      74
engine      20
Source       3
Sink       2
Tee       2 …
```

New command: studio snabb vmprofile <dir>

---

bin/studio

Print useful error messages if any software or hardware dependency is not met.
(Could be that we could be more liberal with platform support but for now I pick Linux/x86-64 as a conservative requirement.)

bin/studio: check for Linux/x86-64 with nix

---

nixpkgs/default.nix
nixpkgs/overlays.nix
nixpkgs/pharo/vm/default.nix
nixpkgs/pharo/vm/share.nix
nixpkgs/studio/frontend/default.nix
nixpkgs/studio/frontend/loadStudio.st

Overlays are functions that transform the Nix packages collection.
Here I am using overlays to add/customize packages instead of forking
nixpkgs. I hope overlays will be an easy way to keep in sync with
upstream nixpkgs.
The 'studio' package is new and covers creating the Pharo VM for
Studio and running that under VNC (with help from ratpoison wm.)

nixpkgs: Add nixpkgs overlay with studio + pharo

---

tools/raptorjit/default.nix

Simple Nix API for running RaptorJIT code:
raptorjit.evalFile <luaSourceFile>:
Evaluate a Lua source file. Provide its output and the trace
data produced during execution.
raptorjit.evalString <luaSource>:
Helper function to call evalFile with code in string.
The standard behavior is to use a special 'auditlog' branch of
RaptorJIT that makes the VM debug symbols (DWARF) available and also
logs the JIT internal data structures (audit.log). So when you run
code with this API it will produce enough information for the UI to
visualize the JIT behavior.
Quick example:
$ nix-build -E 'with import tools/raptorjit {}; evalString "for i = 1, 100 do end"'
$ ls result
audit.log  output.txt  raptorjit.dwo
Have to also include the profiler data soon...

tools/raptorjit: Support running RaptorJIT code

---

backend/bin/inspect
backend/inspector/default.nix
backend/inspector/modules/hexdump.nix
backend/inspector/modules/pcap2xml.nix
backend/inspector/modules/vmprofile.nix

The inspector is a DWIM (do what I mean) interface to the Studio backend.
Studio is able to translate many input formats (e.g. a Snabb process snapshot) into many output formats (e.g. a visualization from R.) The tricky part for an end-user is how to operate it: you probably don't want to have to write a nix expression by hand every time you are inspecting a file.
The solution here is to give the file to the inspector. It will automatically try to process the file in a large number of different ways, most of which will fail because the file won't be the right type, and then it will give you all of the results that built successfully.
So then it is easy to operate the backend. You just pass it a file/directory/url and then browse whatever it happens to spit out.
Currently the processing …

backend: Add inspector (preview)

---

README.md
backend/frontend/default.nix
backend/inspector/default.nix
overlays.nix

Now you install with 'nix-env -iA studio' and that automatically
installs the x11 version, the vnc version, and tigervnc for easy
access to 'vncserver -kill ...'.
So installation is always done in the same way and you choose between
X11 vs VNC when you start Studio.

Installation made simpler

---

backend/frontend/default.nix

This resolves a breakage: Studio imports a Pharo image that is built by the Pharo Jenkins CI, but that CI seems to have flushed the build that we depended on. This update switches to the latest build.
More permanent solution is needed e.g. mirroring the image in permanent storage.

frontend: Update to base Pharo build 24

---

bin/studio

Create a new interface for running studio:
```shell
$ bin/studio vnc     # run in VNC mode
$ bin/studio x11     # run in X11 mode
```
This runs Studio from the current directory without requiring any installation. This is proposed as the default way to run Studio.

Provide updated installation method

---

backend/frontend/default.nix

If the user runs 'studio-x11 ...' then the ... arguments are passed on to the Pharo virtual machine.

studio-x11: Pass command line arguments to Pharo

---

bin/studio

The benefit of --pure should be more obviously seeing dependency errors i.e. it somewhat prevents random software on the host from being visible to Studio.
The benefit of explicitly providing Nix via nix-shell is that we will control the version of Nix that Studio uses.

bin/studio: Use "nix-shell --pure" and explicitly provide nix

---

bin/studio

Current 'studio' script doesn't work,
attributes need to be inputs to the expression
not the expression itself.
The implementation here is similar to how
nix-shell implements "-p attribute":
https://github.com/NixOS/nix/blob/d4dcffd64349bb52ad5f1b184bee5cc7c2be73b4/src/nix-build/nix-build.cc#L250
See also "makeShell" in newer nixpkgs:
https://github.com/NixOS/nixpkgs/blob/adc5c9b83df203c9e425efe00f9a788ed3554c2d/pkgs/build-support/mkshell/default.nix

bin/studio: fix nix-shell invocation

---

backend/pharo/vm/default.nix

After some digging, I figured out my problem wasn’t #48 directly, but ideed plain missing dependencies. I suspect #48 lead to this situation though by masking the problem?
Specifically: pixman, fontconfig, xlibs.{libxcb,libXrender}

pharo-vm: add some missing dependencies

---

bin/studio

Fix regression cause by over-eager enabling of an additional binary cache.

bin/studio: Skip hydra.snabb.co for now

---

frontend/Studio-RaptorJIT/BlockClosure.extension.st
frontend/Studio-RaptorJIT/RJITBytecode.class.st
frontend/Studio-RaptorJIT/RJITBytecodeRecordLog.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st

Text dump to the clipboard for pasting into a local application e.g. Emacs.

Frontend: "Export to clipboard" buttons for Bytecode and IR listings

---

frontend/Studio-RaptorJIT/Integer.extension.st
frontend/Studio-RaptorJIT/RJITIRInstruction.class.st

Allocations are now shown as pink (sunk) or red (unsunk.)
Register names and stack slots are now shown in IR listings.

Frontend: Show RaptorJIT register/stack/sink assignments

---

frontend/Studio-DWARF/DWARFValue.class.st
frontend/Studio-RaptorJIT/Integer.extension.st
frontend/Studio-RaptorJIT/RJITAuditLog.class.st
frontend/Studio-RaptorJIT/RJITFlashback.class.st
frontend/Studio-RaptorJIT/RJITIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITNewCTypeIDEvent.class.st
frontend/Studio-RaptorJIT/RJITPrototype.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st

Generic operand strings like 'str' and 'func' and 'p32' are now replaced by meaningful descriptions of the referenced objects.
This only happens with a version of RaptorJIT that includes sufficient debug information in the auditlog (e.g. lukego/raptorjit@486f720ffbbccd73d5b5a91f0f6dbde6b002aebc). Logs from older RaptorJIT versions will fallback to displaying generic strings.
Screenshot showing function location and hashtable string constant key decoding:

Frontend: Improve RaptorJIT operand decoding

---

frontend/Studio-RaptorJIT/Collection.extension.st
frontend/Studio-RaptorJIT/RJITIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st

The IR listing is now a table with discrete columns. This is handy for alignment and for grouping instructions by sorting them.
The flat textual representation is accessible via the Save icon. This loads it onto the clipboard so you can paste it into an editor.
Screenshot:

Frontend: RaptorJIT IR Listings are now tables

---

frontend/Studio-RaptorJIT/RJITIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st

Clicking on an IR instruction now reveals an object with an "Input Tree" view. This shows the subset of the IR tree showing only the inputs to the selected instruction (transitive closure.)
It's a way to "zoom in" on one instruction and see where its input comes from.
Screenshot of clicking on a problematic instruction (unsunk allocation) to see where its value comes from (click to zoom):

Frontend: Add RaptorJIT "Input Tree" IR view

---

frontend/Studio-RaptorJIT/RJITProcess.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st
frontend/Studio-RaptorJIT/RJITTraceWithProfile.class.st

Specify which root trace is linked.

Frontend: RaptorJIT root trace link '->42' instead of 'root'

---

frontend/Studio-RaptorJIT/RJITAuditLog.class.st
frontend/Studio-RaptorJIT/RJITIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITProcess.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st
frontend/Studio-RaptorJIT/RJITTraceEvent.class.st
frontend/Studio-RaptorJIT/RJITVMProfile.class.st
frontend/Studio-RaptorJIT/RJITVMProfileTrace.class.st

Extend the RaptorJIT view of traces (both collectively and individually.)
Trace List (simple table of traces):
Trace Map (still rough):
Trace Info (summary of one trace):

Frontend: Add "Trace List" and "Trace Map" and "Trace Info"

---

backend/disasm/default.nix
backend/raptorjit/default.nix
bin/studio
frontend/Studio-DWARF/DWARF.class.st
frontend/Studio-DWARF/DWARFEnumerationType.class.st
frontend/Studio-Extension/StudioDAGLayout.class.st
frontend/Studio-RaptorJIT/Collection.extension.st
frontend/Studio-RaptorJIT/RJITAuditLog.class.st
frontend/Studio-RaptorJIT/RJITDisassembler.class.st
frontend/Studio-RaptorJIT/RJITFlashback.class.st
frontend/Studio-RaptorJIT/RJITIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITProcess.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st
frontend/Studio-RaptorJIT/String.extension.st
overlays.nix

Quite a nice update on this branch!
IR instructions are disassembled with mouseover tooltip.
IR instructions that don't generate machine code have dashed borders.
Graph layout switches to Sugiyama (Graphviz) algorithm. This provides the important invariant that each node is placed as high as possible except that it must be below its parents. So the height of each node tells you the maximum dependency chain length through its ancestors. (So tall graphs are quite serial and wide graphs are quite parallel.)
Operands for IR instructions are decoded better especially for `SLOAD` and `FLOAD` and `CALLS`.
PHI instructions are now represented as red arrows. These show how values are updated from one iteration of a loop to the next. The arrow shows where a new value overwrites an old value at the …

RaptorJIT frontend improvements

---

backend/raptorjit/default.nix
bin/studio

Update to latest RaptorJIT (lukego/auditlog branch) and fix `bin/studio` to always use Nix definitions from the working tree (so that edits take effect immediately.)

Nix backend updates

---

backend/raptorjit/default.nix
backend/snabb/default.nix
frontend/Studio-RaptorJIT/RJITProcess.class.st

Studio had included some complicated Nix code for trying to obtain
suitable DWARF debug data for the virtual machine being inspected.
This is not needed with recent versions of RaptorJIT because the DWARF
data is included inline in the log file and can be extracted from
there.
Simple fixes also for loading an audit.log in isolation without
profiler data.

RaptorJIT: Simplify code by assuming that DWARF data is in audit.log

---

frontend/Studio-RaptorJIT/RJITBytecode.class.st
frontend/Studio-RaptorJIT/RJITProcess.class.st
frontend/Studio-RaptorJIT/RJITRootTraceSet.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st

Add a "Call Stack Contour" summary to the trace (Info) tab. This shows only where function calls were entered or exited. It's like a brief summary of the recorded bytecodes log to show which code the trace is covering.
Show VM/MCode/GC percentage summaries for root trace sets (resolves #87.)

Frontend improvements for RaptorJIT

---

frontend/Studio-RaptorJIT/RJITBytecode.class.st
frontend/Studio-RaptorJIT/RJITEvent.class.st
frontend/Studio-RaptorJIT/RJITFlashback.class.st
frontend/Studio-RaptorJIT/RJITIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITProcess.class.st
frontend/Studio-RaptorJIT/RJITPrototype.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st
frontend/Studio-RaptorJIT/String.extension.st

The UI can now read a new 'declname' debug attribute that provides the
declared name of a Lua function. This is used to revamp the UI to make
descriptions of code executed in traces simpler.
Some other improvements coming along for the ride...
The improvements only kick in when using a RaptorJIT version with
declname support.
Trace map and summary:
Trace call stack contour:

Frontend: Add support for RaptorJIT declname

---

Dockerfile
README.md
bin/studio

Allows studio to be run in a docker container without having to install nix locally.
This supports execution in VNC mode. X11 mode should also work if the socket can be exposed inside the docker container in a way that `pharo` can find.

Add Dockerfile

---

backend/frontend/default.nix
bin/studio
frontend/Studio-DWARF/DWARF.class.st
frontend/Studio-Nix/Nix.class.st
frontend/Studio-Nix/Studio.class.st
frontend/Studio-RaptorJIT/FileReference.extension.st
frontend/Studio-RaptorJIT/RJITAuditLog.class.st
frontend/Studio-RaptorJIT/RJITDisassembler.class.st
frontend/Studio-RaptorJIT/RJITIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITProcess.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st
frontend/Studio-RaptorJIT/RJITVMProfile.class.st
overlays.nix

This branch adds initial batch-mode operation for Studio. You can write on the command line
bin/studio decode raptorjit/audit.log textdump
and this will read your RaptorJIT log (or Snabb directory) and write out all the JIT traces in ascii text.
Currently hard-coded for RaptorJIT/Snabb and only handling traces (not profiles etc.) Have to think about the best way to extend in going forward.
Currently also a bit slow and in need of optimization.

Add batch-mode 'bin/studio decode <input> <output>'

---

.travis.yml

Previously Cachix would sometimes be built from source instead of downloaded as binary.

.travis.yml: Install Cachix in Domen-recommended way

---

.travis.yml
README.md

The easiest way to install Studio is with Docker. This is a one-liner and works on Linux, macOS, and Windows. This is now the first suggested method in the README.

README: Revised and with new emphasis on one-liner Docker installation

---

frontend/Studio-RaptorJIT/RJITProcess.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st
frontend/Studio-RaptorJIT/RJITVMProfile.class.st

Support browsing individual VMProfile datasets.

Frontend: Add "VMProfiles" tab to RJITProcess

---

backend/frontend/default.nix
frontend/Studio-RaptorJIT/RJITBlIRFragment.class.st
frontend/Studio-RaptorJIT/RJITBlIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITIRInstruction.class.st
frontend/Studio-RaptorJIT/RJITTrace.class.st

This branch is reintroducing the signature RaptorJIT IR visualizations that were the first feature of Studio but were temporarily lost in the port from "old GToolkit" with Roassal to "new GToolkit" with Bloc.
TODO:
Screenshot:

[wip] Reintroduce IR visualizations

---

backend/Moz2D/default.nix

mozilla-central no longer serves tar balls, only zip.  The buildPhase
converts the zip archive to tar.gz to make the original builder
happy.

Fix downloading of Firefox source
